name: Prod - Build and Deploy

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: ${{ secrets.RUN_REGION }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup Google Cloud CLI
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure docker
      run: |
        gcloud auth configure-docker
   # Build the Docker image
    - name: Build
      run: |
        docker build -t "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$CONTAINER_NAME" \
            --build-arg GITHUB_SHA=$GITHUB_SHA \
            --build-arg GITHUB_REF=$GITHUB_REF .
   # Delete previous existing docker images
    - name: Detele previous images
      run: gcloud container images delete "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$CONTAINER_NAME" --force-delete-tags
      continue-on-error: true
   # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$CONTAINER_NAME"
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$CONTAINER_NAME" \
          --platform "managed" \
          --allow-unauthenticated